const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),ts=require('typescript');
function load(file,mocks={}){const m=new Module(file,module);m.require=id=>id in mocks?mocks[id]:require(id);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports;}
const {createRefreshController}=load('lib/refreshController.ts'),{validateHistory}=load('lib/curationMonitoring.ts');
function environment(){const w=new EventTarget(),d=new EventTarget();d.visibilityState='visible';const timers=new Map();let id=0;w.setTimeout=fn=>{timers.set(++id,fn);return id;};w.clearTimeout=n=>timers.delete(n);w.setInterval=fn=>{timers.set(++id,fn);return id;};w.clearInterval=n=>timers.delete(n);return {window:w,document:d,timers};}
test('manual refresh coalesces overlapping requests and preserves last success on failure',async()=>{const env=environment(),states=[],values=[];let resolve,calls=0;const c=createRefreshController(()=>{calls++;return new Promise(r=>resolve=r);},v=>values.push(v),s=>states.push(s),env);const a=c.refresh();await c.refresh();assert.equal(calls,1);resolve('first');await a;assert.deepEqual(values,['first']);assert.ok(states.at(-1).lastUpdated);c.dispose();assert.equal(env.timers.size,0);});
test('poll, focus, visible and online events refresh; hidden and disposed do not',async()=>{const env=environment();let calls=0;const c=createRefreshController(async()=>++calls,()=>{},()=>{},env);await c.refresh();env.document.visibilityState='hidden';env.window.dispatchEvent(new Event('focus'));assert.equal(calls,1);env.document.visibilityState='visible';env.window.dispatchEvent(new Event('online'));await new Promise(setImmediate);assert.equal(calls,2);[...env.timers.values()][0]();await new Promise(setImmediate);assert.equal(calls,3);env.document.dispatchEvent(new Event('visibilitychange'));await new Promise(setImmediate);assert.equal(calls,4);c.dispose();env.window.dispatchEvent(new Event('focus'));assert.equal(calls,4);});
test('failure retains data and timestamp; timeout aborts and reports a real error',async()=>{const env=environment(),states=[],values=[];let fail=false;const c=createRefreshController(async()=>{if(fail)throw Error('HTTP 401');return 'good';},x=>values.push(x),s=>states.push(s),env);await c.refresh();const at=states.at(-1).lastUpdated;fail=true;await c.refresh();assert.deepEqual(values,['good']);assert.equal(states.at(-1).lastUpdated,at);assert.equal(states.at(-1).error,'HTTP 401');c.dispose();const b=createRefreshController(signal=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('aborted')))),()=>{},s=>states.push(s),env);const pending=b.refresh();[...env.timers.values()].at(-1)();await pending;assert.equal(states.at(-1).error,'Request timed out');b.dispose();});
test('filter-change disposal ignores late old response and cancels requests',async()=>{const env=environment(),values=[];let resolve,signal;const c=createRefreshController(s=>{signal=s;return new Promise(r=>resolve=r);},x=>values.push(x),()=>{},env);const pending=c.refresh();c.dispose();assert.equal(signal.aborted,true);resolve('old');await pending;assert.deepEqual(values,[]);});
test('empty and unavailable histories remain distinct; invalid counts rejected',()=>{assert.deepEqual(validateHistory({runs:[],nextCursor:null,enrichment:false}).runs,[]);const unavailable={runId:'id',reservedAt:'2026-09-10',report:null,counts:null,historyState:'outcomes_unavailable'};assert.equal(validateHistory({runs:[unavailable],nextCursor:'next',enrichment:false}).runs[0].counts,null);assert.throws(()=>validateHistory({runs:[{...unavailable,report:{products:[{}]},counts:{reserved:0}}],nextCursor:null,enrichment:false}),/count mismatch/);});
test('monitor API uses session auth, no-store and cancellation; returns HTTP status',async()=>{let cleared=false,seen;const {apiFetch}=load('lib/api.ts',{'@/lib/auth':{clearToken:()=>cleared=true}});const old=global.fetch;global.fetch=async(url,options)=>{seen=options;return {ok:false,status:401,text:async()=>JSON.stringify({error:'Token expired'})};};try{const signal=new AbortController().signal;await assert.rejects(apiFetch('/admin/recycling-intelligence/runs',{token:'isolated-jwt',cache:'no-store',signal}),e=>e.status===401);assert.equal(seen.cache,'no-store');assert.equal(seen.signal,signal);assert.equal(seen.headers.Authorization,'Bearer isolated-jwt');assert.equal(cleared,true);}finally{global.fetch=old;}});
