"use client";

import { useDashboardLanguage } from "./DashboardLanguage";

const spanish: Record<string, string> = {
  "Overview": "Resumen", "Settings": "Configuración", "History": "Historial", "Back": "Volver",
  "User Detail": "Detalle del usuario", "Brand Detail": "Detalle de la marca", "Partner Detail": "Detalle del socio", "Reward Detail": "Detalle de la recompensa", "Challenge Detail": "Detalle del reto",
  "Products": "Productos", "Product": "Producto", "Rewards": "Recompensas", "Reward": "Recompensa", "User": "Usuario", "Users": "Usuarios", "Partner": "Socio", "Partners": "Socios",
  "Brand admins": "Administradores de marca", "Brand rewards": "Recompensas de marca", "Assigned products": "Productos asignados", "Email": "Correo electrónico", "Display name": "Nombre", "Role": "Rol", "Brand ID": "ID de marca", "Created": "Creado", "Status": "Estado", "Type": "Tipo", "Barcode": "Código de barras", "Units": "Unidades", "Points": "Puntos", "Items": "Productos", "City": "Ciudad", "Wallet": "Monedero", "Code": "Código", "Expires": "Caduca", "Actions": "Acciones",
  "Wallet points": "Puntos del monedero", "Scan events": "Escaneos", "Recycling events": "Eventos de reciclaje", "Recycled units": "Unidades recicladas", "EcoPoints issued": "EcoPoints emitidos", "Active challenges": "Retos activos", "Joined active challenges for this user.": "Retos activos a los que se ha unido este usuario.", "No active joined challenges.": "No hay retos activos inscritos.", "Remove": "Eliminar", "Removing...": "Eliminando...", "Approve": "Aprobar", "Reject": "Rechazar", "Recycling history": "Historial de reciclaje", "Recent scans": "Escaneos recientes", "Trust tier": "Nivel de confianza", "Coordinates": "Coordenadas",
  "Fulfilled unlocks": "Desbloqueos atendidos", "Loaded unlocks": "Desbloqueos cargados", "Active": "Activo", "Inactive": "Inactivo", "Used": "Usado", "Last fulfillment": "Última entrega", "Fulfillment history": "Historial de entregas", "Promo/token": "Promoción/token", "Unlocks": "Desbloqueos", "Active unlocks": "Desbloqueos activos", "Used unlocks": "Desbloqueos usados", "Available codes": "Códigos disponibles", "Access": "Acceso", "Delivery": "Entrega", "Cost": "Coste", "Recent unlocks": "Desbloqueos recientes",
  "Required": "Objetivo", "Shared progress": "Progreso compartido", "Bonus points": "Puntos extra", "Target": "Objetivo", "Completion reward": "Recompensa por completar", "Starts": "Inicio", "Ends": "Fin", "Participant access": "Acceso de participantes", "Invite people or review requests. Emails are never shown on public leaderboards.": "Invita a personas o revisa solicitudes. Los correos nunca aparecen en las clasificaciones públicas.", "Participants": "Participantes", "Participant": "Participante", "Approved recycles": "Reciclajes aprobados", "No participants yet.": "Todavía no hay participantes.", "No rows available.": "No hay filas disponibles.", "Invite": "Invitar", "Inviting...": "Invitando...",
  "Loading user...": "Cargando usuario...", "Loading brand...": "Cargando marca...", "Loading partner...": "Cargando socio...", "Loading reward...": "Cargando recompensa...", "Loading challenge...": "Cargando reto...",
  "Partner CRM": "CRM de socio", "Unlock Queue": "Cola de desbloqueos", "Active Rewards": "Recompensas activas", "Reward Unlocks": "Desbloqueos de recompensas", "Active Unlocks": "Desbloqueos activos", "Assigned Rewards": "Recompensas asignadas", "Used Rewards": "Recompensas usadas", "Expired Unlocks": "Desbloqueos caducados", "Upcoming unlocks": "Próximos desbloqueos", "Active and pending unlocks": "Desbloqueos activos y pendientes", "Expired unlocks": "Desbloqueos caducados", "No expired unlocks.": "No hay desbloqueos caducados.", "No active unlocks.": "No hay desbloqueos activos.", "Partner-scoped reward tokens only.": "Solo tokens de recompensa asignados a este socio.", "Customer": "Cliente", "Token": "Token", "Redeemed": "Canjeado", "Loading unlocks...": "Cargando desbloqueos...", "Loading history...": "Cargando historial...", "No used rewards yet.": "Todavía no hay recompensas usadas.", "Used reward history": "Historial de recompensas usadas", "Assigned active rewards": "Recompensas activas asignadas", "Loading rewards...": "Cargando recompensas...", "No active rewards assigned from current unlocks.": "No hay recompensas activas asignadas en los desbloqueos actuales.", "Recent used rewards": "Recompensas usadas recientemente", "Partner profile": "Perfil del socio", "Signed-in email": "Correo de la sesión", "User ID": "ID de usuario", "Workspace": "Espacio de trabajo", "Permissions": "Permisos", "Partner-scoped fulfillment only": "Solo entregas asignadas al socio", "No expiry": "Sin caducidad",
  "Sponsored challenges": "Retos patrocinados", "Create challenge": "Crear reto", "Campaign and benefit": "Campaña y beneficio", "Challenge title": "Título del reto", "Banner image URL": "URL de la imagen", "Description": "Descripción", "Eligible recycling": "Reciclaje válido", "Any product": "Cualquier producto", "Any of our products": "Cualquiera de nuestros productos", "Selected products": "Productos seleccionados", "Recycles to unlock": "Reciclajes para desbloquear", "Optional collective goal": "Objetivo colectivo opcional", "Countries (ISO codes, blank means worldwide)": "Países (códigos ISO; vacío significa todo el mundo)", "Eligible products": "Productos válidos", "Benefit title": "Título del beneficio", "Estimated saving": "Ahorro estimado", "Benefit description": "Descripción del beneficio", "Affiliate link": "Enlace de afiliado", "Affiliate link + promo code": "Enlace de afiliado + código promocional", "Affiliate URL": "URL de afiliado", "Promo code": "Código promocional", "Hours available after unlock": "Horas disponibles tras desbloquear", "User instructions": "Instrucciones para el usuario", "Submitting...": "Enviando...", "Submit for GreenLoop review": "Enviar a revisión de GreenLoop", "No sponsored challenges yet.": "Todavía no hay retos patrocinados.", "Delete": "Eliminar", "Submitted for GreenLoop review.": "Enviado a revisión de GreenLoop.", "Submitted for GreenLoop review. Refresh to see the updated list.": "Enviado a revisión de GreenLoop. Actualiza para ver la lista.", "Invite recyclers to complete an earned brand journey.": "Invita a los usuarios a completar un reto de reciclaje de tu marca."
};

export function useWorkspaceLabels() {
  const { language } = useDashboardLanguage();
  return (label: string) => language === "es" ? spanish[label] ?? label : label;
}

export function WorkspaceLabel({ text }: { text: string }) {
  const t = useWorkspaceLabels();
  return <>{t(text)}</>;
}
