"use client";

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { WorkspaceHeader } from '@/components/crm/WorkspaceHeader';
import { useDashboardLanguage } from '@/components/crm/DashboardLanguage';
import styles from '@/components/crm/Workspace.module.css';
import { apiFetch } from '@/lib/api';
import { getToken } from '@/lib/auth';

type Totals = {uniqueUsers:number;sessions:number;events:number;newAccounts:number;firstTimeUsers:number;returningUsers:number;approved:number;submissions:number;recyclingUsers:number;verifiedItems:number;points:number;affectedUsers:number;frictionEvents:number;pending:number;rejected:number};
type Entry = {id:string;kind:'daily'|'weekly';report_date:string;period_start:string;period_end:string;generated_at:string;totals:Totals};
type User = {user_id:string;display_name:string;events:number;sessions:number;active_days:number;attempts:number;approved:number;submissions:number;verified_items:number;points:number;friction_events:number;recycling_days:number;meaningful_actions:number};
type Report = {id:string;generated_at:string;payload:{kind:string;reportDate:string;periodStart:string;periodEnd:string;totals:Totals;users:User[];daily:{date:string;users:number;sessions:number;approved:number}[];screens:{screen:string;views:number;users:number}[];steps:{event_name:string;events:number;users:number}[];friction:{event_name:string;screen:string;app_version:string;platform:string;events:number;users:number}[];findings:string[];definitions:string[];health:{lastEvent:string|null;eventsMissingSession:number;excludedAccounts:number;explicitTestExclusions:number}}};
type Timeline = {displayName:string;truncated:boolean;note:string;events:{created_at:string;action:string;screen:string|null;app_version:string|null;platform:string|null;source:string;status:string|null}[]};
const endpoint='/admin/reports/app-analytics/archive';
const panel='rounded-lg border border-[var(--gl-hairline)] bg-[var(--gl-paper)] p-4';
const control='rounded-md border border-[var(--gl-hairline)] bg-[var(--gl-paper)] px-3 py-2 text-sm';
function dateText(value:string) {return value.slice(0,10);}
function endDate(value:string) {const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10);}
function human(value:string|null) {return value?.replaceAll('_',' ') || '—';}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}) {return <table className={styles.table}><thead><tr>{headers.map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td className="p-2" key={j} data-label={headers[j]}>{v}</td>)}</tr>):<tr><td className="p-3 text-[var(--gl-ink-muted)]" colSpan={headers.length}>—</td></tr>}</tbody></table>;}
export function AdminAppAnalyticsReports() {
  const router=useRouter();const {language}=useDashboardLanguage();const es=language==='es';
  const [entries,setEntries]=useState<Entry[]>([]),[selected,setSelected]=useState(''),[report,setReport]=useState<Report|null>(null),[timeline,setTimeline]=useState<Timeline|null>(null);
  const [error,setError]=useState(''),[busy,setBusy]=useState(true),[detailBusy,setDetailBusy]=useState(false),[timelineBusy,setTimelineBusy]=useState(false);
  const [kind,setKind]=useState('all'),[search,setSearch]=useState(''),[ranking,setRanking]=useState('approved');
  useEffect(()=>{let active=true;const token=getToken();if(!token){router.replace('/login');return;}
    apiFetch<{reports:Entry[]}>(endpoint,{token}).then(r=>{if(active){setEntries(r.reports);setDetailBusy(Boolean(r.reports.length));setSelected(r.reports[0]?.id||'');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[router]);
  useEffect(()=>{let active=true;if(!selected)return;
    apiFetch<Report>(`${endpoint}/${selected}`,{token:getToken()||''}).then(r=>{if(active)setReport(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setDetailBusy(false);});return()=>{active=false;};},[selected]);
  const [userId,setUserId]=useState('');
  useEffect(()=>{let active=true;if(!userId||!selected)return;
    apiFetch<Timeline>(`${endpoint}/${selected}/users/${userId}`,{token:getToken()||''}).then(r=>{if(active)setTimeline(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setTimelineBusy(false);});return()=>{active=false;};},[selected,userId]);
  const users=useMemo(()=>[...(report?.payload.users||[])].filter(u=>`${u.display_name} ${u.user_id}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b[ranking as keyof User])-Number(a[ranking as keyof User])||b.approved-a.approved),[report,search,ranking]);
  const p=report?.payload,t=p?.totals;
  const metrics=t?[[es?'Usuarios únicos':'Unique tracked users',t.uniqueUsers],[es?'Sesiones registradas':'Recorded sessions',t.sessions],[es?'Primer uso registrado':'First recorded visit',t.firstTimeUsers],[es?'Usuarios recurrentes':'Returning users',t.returningUsers],[es?'Reciclajes aprobados':'Approved recycling',t.approved],[es?'Usuarios que reciclan':'Recycling users',t.recyclingUsers],[es?'Usuarios con fricción':'Users with friction',t.affectedUsers]]:[];
  return <div className={`${styles.root} space-y-4`}>
    <WorkspaceHeader><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">{es?'Analítica de app':'App Analytics'}</h1><Link className={control} href="/admin/reports/app-analytics?view=live">{es?'Explorar analítica en vivo':'Explore live analytics'}</Link></div></WorkspaceHeader>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{es?'Informes diarios y semanales':'Daily & weekly reports'}</h2><p className="mt-1 text-sm text-[var(--gl-ink-muted)]">{es?'Cada día a las 08:00 · Resumen cada domingo · Europe/Madrid':'Every day at 08:00 · Weekly summary every Sunday · Europe/Madrid'}</p></div><label className="text-sm">{es?'Tipo':'Type'} <select className={control} value={kind} onChange={e=>{setKind(e.target.value);const first=entries.find(r=>e.target.value==='all'||r.kind===e.target.value);setUserId('');setTimeline(null);setTimelineBusy(false);setReport(null);setDetailBusy(Boolean(first));setError('');setSelected(first?.id||'');}}><option value="all">{es?'Todos':'All reports'}</option><option value="daily">{es?'Diario':'Daily'}</option><option value="weekly">{es?'Semanal':'Weekly'}</option></select></label></div>
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}
    {busy?<p role="status">{es?'Cargando informes…':'Loading reports…'}</p>:<div className={panel}><label className="block text-sm font-medium" htmlFor="analytics-report">{es?'Seleccionar informe':'Select report'}</label><select id="analytics-report" className={`${control} mt-2 w-full`} value={selected} onChange={e=>{setUserId('');setTimeline(null);setTimelineBusy(false);setReport(null);setDetailBusy(true);setError('');setSelected(e.target.value);}}>{entries.filter(e=>kind==='all'||e.kind===kind).map(e=><option key={e.id} value={e.id}>{e.kind==='weekly'?(es?'Resumen semanal':'Weekly summary'):(es?'Informe diario':'Daily report')} · {dateText(e.report_date)} · {e.totals.uniqueUsers} {es?'usuarios':'users'}</option>)}</select>{!entries.length&&<p className="mt-3 text-sm">{es?'Aún no hay informes generados.':'No reports have been generated yet.'}</p>}</div>}
    {detailBusy&&<p role="status">{es?'Cargando detalle…':'Loading report…'}</p>}
    {p&&t&&<>
      <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{p.kind==='weekly'?(es?'Resumen semanal':'Weekly summary'):(es?'Informe diario':'Daily report')} · {p.periodStart}{p.kind==='weekly'?` — ${endDate(p.periodEnd)}`:''}</h2><span className="text-xs text-[var(--gl-ink-muted)]">{es?'Generado':'Generated'} {new Date(report!.generated_at).toLocaleString(es?'es-ES':'en-GB',{timeZone:'Europe/Madrid'})}</span></div>
      <div className={styles.metrics}>{metrics.map(([name,value])=><div key={name}><p className="text-xs text-[var(--gl-ink-muted)]">{name}</p><p className="text-2xl font-semibold">{value}</p></div>)}</div>
      <p className="text-xs text-[var(--gl-ink-muted)]">{es?'Usuarios identificados con actividad registrada; no incluye aperturas anónimas. Las sesiones históricas no equivalen a tiempo activo.':'Logged-in accounts with recorded activity; anonymous opens are not measured. Historical sessions do not establish active time.'}</p>
      <section className={panel}><h3 className="mb-3 font-semibold">{es?'Hallazgos':'Findings'}</h3><ul className="list-disc space-y-2 pl-5 text-sm">{p.findings.map(f=><li key={f}>{f}</li>)}</ul></section>
      <section className={panel}><h3 className="mb-3 font-semibold">{es?'Actividad por día':'Activity by day'}</h3><Table headers={[es?'Día':'Day',es?'Usuarios únicos':'Unique users',es?'Sesiones':'Sessions',es?'Reciclajes aprobados':'Approved recycling']} rows={p.daily.map(d=>[d.date,d.users,d.sessions,d.approved])}/></section>
      <section className={panel}><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{es?'Actividad individual y usuarios destacados':'Individual activity & top users'}</h3><p className="mt-1 text-xs text-[var(--gl-ink-muted)]">{es?'Selecciona un usuario para ver su cronología.':'Select a user to inspect their timeline.'}</p></div><div className="flex flex-wrap gap-2"><input aria-label={es?'Buscar usuario':'Search users'} className={control} placeholder={es?'Buscar usuario':'Search users'} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={es?'Clasificación':'Rank users by'} className={control} value={ranking} onChange={e=>setRanking(e.target.value)}><option value="approved">{es?'Más reciclaje':'Most recycling'}</option><option value="active_days">{es?'Más días activos':'Most active days'}</option><option value="recycling_days">{es?'Más días reciclando':'Most recycling days'}</option><option value="meaningful_actions">{es?'Más acciones en recompensas/retos':'Most reward/challenge actions'}</option><option value="friction_events">{es?'Más fricción':'Most friction'}</option></select></div></div>
      <Table headers={[es?'Usuario':'User',es?'Días activos':'Active days',es?'Sesiones':'Sessions',es?'Eventos':'Events',es?'Intentos':'Submit attempts',es?'Aprobados':'Approved',es?'Artículos':'Item records',es?'Puntos':'Points',es?'Fricción':'Friction']} rows={users.map(u=>[<button className="text-left font-medium text-[var(--gl-green)] underline underline-offset-4" key={u.user_id} onClick={()=>{if(userId!==u.user_id){setTimeline(null);setTimelineBusy(true);setUserId(u.user_id);}}}>{u.display_name}<span className="block text-xs font-normal text-[var(--gl-ink-muted)]">{u.user_id.slice(0,8)}</span></button>,u.active_days,u.sessions,u.events,u.attempts,u.approved,u.verified_items,u.points,u.friction_events])}/></section>
      {timelineBusy&&<p role="status">{es?'Cargando actividad…':'Loading user activity…'}</p>}
      {timeline&&<section className={panel}><div className="flex justify-between gap-3"><h3 className="font-semibold">{timeline.displayName} · {es?'Cronología':'Activity timeline'}</h3><button className={control} onClick={()=>{setUserId('');setTimeline(null);}}>{es?'Cerrar':'Close'}</button></div><p className="my-2 text-xs text-[var(--gl-ink-muted)]">{timeline.note}{timeline.truncated?' Showing the latest 500 events.':''}</p><Table headers={[es?'Hora':'Time',es?'Acción':'Action',es?'Pantalla':'Screen',es?'Fuente':'Source',es?'Estado / puntos':'Status / points',es?'Versión':'Version']} rows={timeline.events.map(e=>[new Date(e.created_at).toLocaleString(es?'es-ES':'en-GB',{timeZone:'Europe/Madrid'}),human(e.action),human(e.screen),e.source,human(e.status),e.app_version||'—'])}/></section>}
      <div className="grid gap-4 xl:grid-cols-2"><section className={panel}><h3 className="mb-3 font-semibold">{es?'Reciclaje y resultados':'Recycling outcomes'}</h3><Table headers={[es?'Métrica':'Metric',es?'Total':'Total']} rows={[[es?'Enviados':'Submissions',t.submissions],[es?'Aprobados':'Approved',t.approved],[es?'Rechazados':'Rejected / failed',t.rejected],[es?'Pendientes / otros':'Pending / other',t.pending],[es?'Artículos verificados':'Verified item records',t.verifiedItems],[es?'Puntos emitidos':'Ledger points issued',t.points],[es?'Nuevas cuentas':'New accounts',t.newAccounts]]}/></section><section className={panel}><h3 className="mb-3 font-semibold">{es?'Pantallas principales':'Top screens'}</h3><Table headers={[es?'Pantalla':'Screen',es?'Vistas':'Views',es?'Usuarios':'Users']} rows={p.screens.map(s=>[human(s.screen),s.views,s.users])}/></section></div>
      <section className={panel}><h3 className="mb-3 font-semibold">{es?'Fricción registrada':'Recorded friction'}</h3>{!p.friction.length&&<p className="mb-2 text-sm text-[var(--gl-ink-muted)]">{es?'No se registraron eventos de fricción. Esto no demuestra ausencia de problemas.':'No tracked friction events. This does not establish that users encountered no problems.'}</p>}<Table headers={[es?'Evento':'Event',es?'Pantalla':'Screen',es?'Versión':'Version',es?'Plataforma':'Platform',es?'Eventos':'Events',es?'Usuarios':'Users']} rows={p.friction.map(f=>[human(f.event_name),human(f.screen),f.app_version||'—',f.platform||'—',f.events,f.users])}/></section>
      <details className={panel}><summary className="cursor-pointer font-semibold">{es?'Pasos registrados y definiciones':'Tracked steps & metric definitions'}</summary><p className="my-3 text-sm">{es?'Los recuentos no constituyen un embudo de conversión ordenado.':'These counts are not an ordered conversion funnel.'}</p><Table headers={[es?'Paso':'Step',es?'Eventos':'Events',es?'Usuarios':'Users']} rows={p.steps.map(s=>[human(s.event_name),s.events,s.users])}/><ul className="mt-4 list-disc space-y-2 pl-5 text-sm">{p.definitions.map(d=><li key={d}>{d}</li>)}</ul><p className="mt-4 text-xs text-[var(--gl-ink-muted)]">Excluded accounts: {p.health.excludedAccounts} · Explicit test exclusions: {p.health.explicitTestExclusions} · Events missing session: {p.health.eventsMissingSession} · Latest recorded event: {p.health.lastEvent||'None'}</p></details>
    </>}
  </div>;
}
