'use client';
import {Info} from 'lucide-react';
import type {Outcomes} from '@/lib/curationOutcomes';
import type {ReactNode} from 'react';
import {LatestImprovements} from './LatestImprovements';

export function IntelligenceStatistics({data,language,format,onPending,onProduct,activity}:{data:Outcomes;language:'en'|'es';format:(v:string)=>string;onPending:()=>void;onProduct:(barcode:string)=>void;activity?:ReactNode}){
 const es=language==='es',t=(en:string,sp:string)=>es?sp:en;
 const n=(v:number|null|undefined)=>v==null?'—':v.toLocaleString(language);
 const stat=(label:string,value:number|null|undefined)=><div><dd className='text-xl font-semibold tabular-nums'>{n(value)}</dd><dt className='text-sm text-stone-600'>{label}</dt></div>;
 return <>
  <section aria-label={t('Catalogue progress','Progreso del catálogo')} className='bg-white p-4'>
   <div className='flex items-center justify-between gap-3'><h2 className='font-semibold'>{t('Complete products','Productos completos')}</h2><details className='relative'><summary aria-label={t('About these statistics','Acerca de estas estadísticas')} title={t('About these statistics','Acerca de estas estadísticas')} className='flex h-11 w-11 cursor-pointer list-none items-center justify-center'><Info size={19}/></summary><div className='absolute right-0 z-20 w-72 max-w-[80vw] rounded border bg-white p-3 text-sm shadow'>
    <p>{t('Complete means name, brand, photo and packaging are present. Each counts for 25%; this is not an accuracy score.','Completo significa nombre, marca, foto y envase presentes. Cada uno vale 25%; no mide exactitud.')}</p>
    <p className='mt-2'>{t('Packaging identified means the main packaging has a material and type. This does not certify accuracy. Partial records are excluded. Queue status also considers pending decisions and recycling guidance.','Envase identificado significa que el envase principal tiene material y tipo. No certifica exactitud. Los registros parciales no cuentan. La cola también considera decisiones pendientes y guía de reciclaje.')}</p>
    <p className='mt-2'>{n(data.classified)} {t('products have a packaging record, including partial records.','productos tienen un registro de envase, incluidos los parciales.')}</p>
    <p className='mt-2'>{t('Improvements count distinct products with Intelligence-supported changes still in use. Proposals, unchanged saves and rolled-back changes do not count. Latest batch means the latest completed run.','Las mejoras cuentan productos distintos con cambios de Inteligencia aún vigentes. No cuentan propuestas, guardados sin cambios ni cambios revertidos. Último lote significa el último terminado.')}</p>
    <p className='mt-2'>{t('Missing-field and improvement counts can overlap: one product may appear under several fields. Saved proposals are unapplied findings, not a count of mandatory approvals.','Los recuentos por dato pueden coincidir: un producto puede aparecer en varios. Las propuestas guardadas son hallazgos sin aplicar, no aprobaciones obligatorias.')}</p>
   </div></details></div>
   <div className='my-2 flex flex-wrap items-baseline gap-x-3'><strong className='text-3xl font-semibold tabular-nums'>{data.completePercent==null?'—':n(data.completePercent)+'%'}</strong><span>{n(data.completeProducts)} / {n(data.totalProducts)} {t('complete','completos')}</span></div>
   {data.completePercent!=null?<div role='progressbar' aria-label={t('Complete products','Productos completos')} aria-valuemin={0} aria-valuemax={data.totalProducts} aria-valuenow={data.completeProducts} className='h-2 overflow-hidden rounded bg-stone-200'><div className='h-full bg-emerald-700' style={{width:data.completePercent+'%'}}/></div>:null}
   <dl className='mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3'>
    {stat(t('Total products','Productos totales'),data.totalProducts)}
    {stat(t('Packaging identified','Envase identificado'),data.totalProducts==null?null:data.totalProducts-data.gaps.packaging)}
    <div><dd className='text-xl font-semibold tabular-nums'>{n(data.pendingCount)}</dd><dt><button onClick={onPending} className='min-h-11 text-left text-sm text-emerald-800 underline'>{t('View saved proposals','Ver propuestas guardadas')}</button></dt></div>
   </dl>
   <div className='mt-3 border-t pt-3'><h3 className='font-semibold'>{n(data.missingInformation)} {t('products need information','productos necesitan información')}</h3><p className='mt-1 text-sm text-stone-600'>{t('Of these:','De estos:')}</p>
   <dl aria-label={t('Missing information breakdown','Información que falta')} className='mt-2 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4'>{Object.entries(data.gaps).map(([k,v])=><div key={k} className='flex justify-between gap-2'><dt>{({name:t('Missing name','Sin nombre'),brand:t('Missing brand','Sin marca'),photo:t('Missing photo','Sin foto'),packaging:t('Missing packaging','Sin envase')} as Record<string,string>)[k]}</dt><dd className='font-semibold tabular-nums'>{n(v)}</dd></div>)}</dl></div>
   <p className='mt-3 text-xs text-stone-500'>{format(data.asOf)}</p>
  </section>
  <section aria-label={t('Live improvements','Mejoras aplicadas')} className='bg-white p-4'><h2 className='font-semibold'>{t('Live improvements','Mejoras aplicadas')}</h2><dl className='mt-3 grid grid-cols-2 gap-4 sm:grid-cols-4'>
   {stat(t('Intelligence · all time','Inteligencia · total'),data.contributions?.intelligence.improvedProducts)}
   {stat(t('Last 24 hours','Últimas 24 horas'),data.improvedLast24Hours)}
   {stat(t('Latest completed batch','Último lote terminado'),data.improvedLatestBatch)}
   {stat(t('Photos published','Fotos publicadas'),data.photosAdded)}
  </dl>{data.latestBatch?<p className='mt-3 text-xs text-stone-500'>{t('Latest batch','Último lote')}: {format(data.latestBatch.endedAt)}</p>:null}</section>
  <LatestImprovements items={data.recentImprovements} language={language} format={format} onProduct={onProduct}/>
  {activity}
  <details aria-label={t('Intelligence Contribution','Aportaciones')} className='bg-white p-4'><summary className='min-h-11 cursor-pointer py-2 font-semibold'>{t('Intelligence Contribution','Aportaciones')}</summary><div className='flex justify-end'><details className='relative'><summary aria-label={t('About contribution counts','Acerca de las aportaciones')} title={t('About contribution counts','Acerca de las aportaciones')} className='flex h-11 w-11 cursor-pointer list-none items-center justify-center'><Info size={19}/></summary><p className='absolute right-0 z-20 w-72 max-w-[80vw] rounded border bg-white p-3 text-sm shadow'>{t('Open Food Facts counts records with that source, not complete imports. Products may have multiple sources. User photos count distinct products with non-rejected submissions, not uploads. Published counts only current publications linked to user photos, not all user-supported metadata changes. Original import completeness was not recorded.','Open Food Facts cuenta registros con esa fuente, no importaciones completas. Un producto puede tener varias fuentes. Las fotos cuentan productos distintos con envíos no rechazados, no archivos. Publicadas cuenta solo publicaciones vigentes vinculadas a fotos de usuarios, no todos los cambios de datos respaldados por usuarios. No se registró la integridad original al importar.')}</p></details></div>
   <dl className='divide-y text-sm'><div className='flex flex-wrap justify-between gap-2 py-3'><dt>Open Food Facts</dt><dd><strong>{n(data.contributions?.openFoodFacts.products)}</strong> {t('catalogue records','registros del catálogo')}</dd></div>
   <div className='py-3'><dt className='font-semibold'>GreenLoop Intelligence</dt><dd><p className='mt-1'><strong>{n(data.contributions?.intelligence.improvedProducts)}</strong> {t('products improved','productos mejorados')}</p><ul aria-label={t('Improvements by field','Mejoras por dato')} className='mt-2 list-disc space-y-1 pl-5'>{(['name','brand','photo','packaging'] as const).map(field=><li key={field}>{({name:t('Names','Nombres'),brand:t('Brands','Marcas'),photo:t('Photos','Fotos'),packaging:t('Packaging','Envases')})[field]}: <strong>{n(data.contributions?.intelligence.fields?.[field])}</strong></li>)}</ul></dd></div>
   <div className='py-3'><dt className='font-semibold'>{t('User contributions','Aportaciones de usuarios')}</dt><dd><ul className='mt-2 list-disc space-y-1 pl-5'><li>{t('Products photographed','Productos fotografiados')}: <strong>{n(data.contributions?.users.products)}</strong></li><li>{t('Photos published','Fotos publicadas')}: <strong>{n(data.contributions?.users.improvedProducts)}</strong> <span className='text-stone-500'>{t('(included above)','(incluidas arriba)')}</span></li></ul></dd></div></dl>
   <details className='border-t pt-2'><summary className='min-h-11 cursor-pointer py-2 font-medium'>{t('Top contributing users','Usuarios que más contribuyen')}</summary><ul className='divide-y text-sm'>{data.topContributors?.map(u=><li key={u.id} className='py-3'><strong>{u.name}</strong><ul className='mt-2 list-disc space-y-1 pl-5'><li>{t('Products photographed','Productos fotografiados')}: <strong>{n(u.products)}</strong></li><li>{t('Photos published','Fotos publicadas')}: <strong>{n(u.improvedProducts)}</strong></li></ul></li>)}</ul>{!data.topContributors?.length?<p className='py-2 text-sm text-stone-500'>{t('No attributed contributions recorded.','No hay aportaciones atribuidas.')}</p>:null}</details>
  </details>
 </>;
}
